// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ReconcileDocs.Infrastructure.Persistence;

#nullable disable

namespace ReconcileDocs.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429100000_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ReconcileDocs.Domain.Entities.DocumentUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DocumentKind")
                        .HasColumnType("integer")
                        .HasColumnName("document_kind");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("original_file_name");

                    b.Property<int>("ReconcileStatus")
                        .HasColumnType("integer")
                        .HasColumnName("reconcile_status");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_document_uploads");

                    b.ToTable("document_uploads");
                });

            modelBuilder.Entity("ReconcileDocs.Domain.Entities.ParsedDocumentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("DocumentUploadId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_upload_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<string>("SourceParser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_parser");

                    b.Property<DateOnly?>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.HasKey("Id")
                        .HasName("pk_parsed_document_rows");

                    b.HasIndex("DocumentUploadId")
                        .HasDatabaseName("ix_parsed_document_rows_document_upload_id");

                    b.ToTable("parsed_document_rows");
                });

            modelBuilder.Entity("ReconcileDocs.Domain.Entities.ReconcileMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsMatched")
                        .HasColumnType("boolean")
                        .HasColumnName("is_matched");

                    b.Property<Guid>("ReconcileRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("reconcile_run_id");

                    b.Property<int>("SpreadsheetRowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("spreadsheet_row_number");

                    b.Property<int>("StatementRowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("statement_row_number");

                    b.HasKey("Id")
                        .HasName("pk_reconcile_matches");

                    b.HasIndex("ReconcileRunId")
                        .HasDatabaseName("ix_reconcile_matches_reconcile_run_id");

                    b.ToTable("reconcile_matches");
                });

            modelBuilder.Entity("ReconcileDocs.Domain.Entities.ReconcileRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_message");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.Property<int>("MatchedCount")
                        .HasColumnType("integer")
                        .HasColumnName("matched_count");

                    b.Property<string>("ParserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parser_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("SpreadsheetUploadId")
                        .HasColumnType("uuid")
                        .HasColumnName("spreadsheet_upload_id");

                    b.Property<Guid>("StatementUploadId")
                        .HasColumnType("uuid")
                        .HasColumnName("statement_upload_id");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<int>("UnmatchedCount")
                        .HasColumnType("integer")
                        .HasColumnName("unmatched_count");

                    b.Property<Guid?>("TemplateDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_definition_id");

                    b.HasKey("Id")
                        .HasName("pk_reconcile_runs");

                    b.HasIndex("SpreadsheetUploadId")
                        .HasDatabaseName("ix_reconcile_runs_spreadsheet_upload_id");

                    b.HasIndex("StatementUploadId")
                        .HasDatabaseName("ix_reconcile_runs_statement_upload_id");

                    b.HasIndex("TemplateDefinitionId")
                        .HasDatabaseName("ix_reconcile_runs_template_definition_id");

                    b.ToTable("reconcile_runs");
                });

            modelBuilder.Entity("ReconcileDocs.Domain.Entities.TemplateDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("configuration_json");

                    b.Property<int>("DocumentKind")
                        .HasColumnType("integer")
                        .HasColumnName("document_kind");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ParserKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("parser_key");

                    b.HasKey("Id")
                        .HasName("pk_template_definitions");

                    b.ToTable("template_definitions");
                });

            modelBuilder.Entity("ReconcileDocs.Domain.Entities.ParsedDocumentRow", b =>
                {
                    b.HasOne("ReconcileDocs.Domain.Entities.DocumentUpload", null)
                        .WithMany()
                        .HasForeignKey("DocumentUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReconcileDocs.Domain.Entities.ReconcileMatch", b =>
                {
                    b.HasOne("ReconcileDocs.Domain.Entities.ReconcileRun", null)
                        .WithMany()
                        .HasForeignKey("ReconcileRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReconcileDocs.Domain.Entities.ReconcileRun", b =>
                {
                    b.HasOne("ReconcileDocs.Domain.Entities.DocumentUpload", null)
                        .WithMany()
                        .HasForeignKey("SpreadsheetUploadId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReconcileDocs.Domain.Entities.DocumentUpload", null)
                        .WithMany()
                        .HasForeignKey("StatementUploadId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReconcileDocs.Domain.Entities.TemplateDefinition", null)
                        .WithMany()
                        .HasForeignKey("TemplateDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
        }
    }
}