// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReconcileDocs.Infrastructure.Persistence;

#nullable disable

namespace ReconcileDocs.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429110005_SyncModelSnapshot")]
    partial class SyncModelSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReconcileDocs.Domain.Entities.DocumentUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<int>("DocumentKind")
                        .HasColumnType("integer")
                        .HasColumnName("document_kind");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("original_file_name");

                    b.Property<int>("ReconcileStatus")
                        .HasColumnType("integer")
                        .HasColumnName("reconcile_status");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at_utc");

                    b.HasKey("Id");

                    b.ToTable("document_uploads", (string)null);
                });

            modelBuilder.Entity("ReconcileDocs.Domain.Entities.ParsedDocumentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("DocumentUploadId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_upload_id");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<string>("SourceParser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_parser");

                    b.Property<DateOnly?>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.HasKey("Id");

                    b.ToTable("parsed_document_rows", (string)null);
                });

            modelBuilder.Entity("ReconcileDocs.Domain.Entities.ReconcileMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsMatched")
                        .HasColumnType("boolean")
                        .HasColumnName("is_matched");

                    b.Property<Guid>("ReconcileRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("reconcile_run_id");

                    b.Property<int>("SpreadsheetRowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("spreadsheet_row_number");

                    b.Property<int>("StatementRowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("statement_row_number");

                    b.HasKey("Id");

                    b.ToTable("reconcile_matches", (string)null);
                });

            modelBuilder.Entity("ReconcileDocs.Domain.Entities.ReconcileRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_message");

                    b.Property<int>("MatchedCount")
                        .HasColumnType("integer")
                        .HasColumnName("matched_count");

                    b.Property<string>("ParserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parser_name");

                    b.Property<Guid>("SpreadsheetUploadId")
                        .HasColumnType("uuid")
                        .HasColumnName("spreadsheet_upload_id");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<Guid>("StatementUploadId")
                        .HasColumnType("uuid")
                        .HasColumnName("statement_upload_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("TemplateDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_definition_id");

                    b.Property<int>("UnmatchedCount")
                        .HasColumnType("integer")
                        .HasColumnName("unmatched_count");

                    b.HasKey("Id");

                    b.ToTable("reconcile_runs", (string)null);
                });

            modelBuilder.Entity("ReconcileDocs.Domain.Entities.TemplateDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("configuration_json");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DocumentKind")
                        .HasColumnType("integer")
                        .HasColumnName("document_kind");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ParserKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("parser_key");

                    b.HasKey("Id");

                    b.ToTable("template_definitions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
